-- 코드를 입력하세요
SELECT PRODUCT.PRODUCT_CODE, PRODUCT.PRICE*sum(OFFLINE_SALE.SALES_AMOUNT) as 'sales'
from PRODUCT, OFFLINE_SALE
where PRODUCT.PRODUCT_ID = OFFLINE_SALE.PRODUCT_ID
group by OFFLINE_SALE.PRODUCT_ID
order by sales desc, PRODUCT.PRODUCT_CODE asc;