-- 코드를 입력하세요
SELECT TITLE, USED_GOODS_REPLY.BOARD_ID, USED_GOODS_REPLY.REPLY_ID, USED_GOODS_REPLY.WRITER_ID, USED_GOODS_REPLY.CONTENTS, DATE_FORMAT(USED_GOODS_REPLY.CREATED_DATE, '%Y-%m-%d')
from USED_GOODS_REPLY, USED_GOODS_BOARD
where USED_GOODS_REPLY.BOARD_ID=USED_GOODS_BOARD.BOARD_ID and USED_GOODS_BOARD.CREATED_DATE LIKE '2022-10%'
order by USED_GOODS_REPLY.CREATED_DATE, USED_GOODS_BOARD.TITLE