-- 코드를 입력하세요
SELECT BOOK_ID, AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') as PUBLISHED_DATE
from BOOK, AUTHOR
where AUTHOR.AUTHOR_ID = BOOK.AUTHOR_ID and BOOK.CATEGORY = '경제'
order by PUBLISHED_DATE;